# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  env: 
    DRIVE_ID: $(DRIVE_ID)
  inputs:
    targetType: 'inline'
    script: echo -e "team_drive = $DRIVE_ID" >> config/rclone/rclone.conf
- task: Bash@3
  displayName: 'rclone'
  env:
    DRIVE_SERVICE_ACCOUNT_CREDENTIALS: $(DRIVE_SERVICE_ACCOUNT_CREDENTIALS)
  inputs:
    targetType: 'inline'
    script: |
      docker run --rm \
        --volume $(Build.SourcesDirectory)/config/rclone:/config/rclone \
        --volume $(Build.SourcesDirectory)/root:/root \
        --env RCLONE_DRIVE_SERVICE_ACCOUNT_CREDENTIALS="$DRIVE_SERVICE_ACCOUNT_CREDENTIALS" \
        rclone/rclone \
        sync -v /root gdrive:WalletStationDocs
