# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: secureEnv
  displayName: "Downloading secure file"
  inputs:
    secureFile: 'wallet-station-docs-1a24d107ddeb.txt'
- task: Bash@3
  displayName: 'rclone'
  env:
    DRIVE_SERVICE_ACCOUNT_CREDENTIALS: $(DRIVE_SERVICE_ACCOUNT_CREDENTIALS)
  inputs:
    targetType: 'inline'
    script: |
      docker run --rm \
        --volume Build.SourcesDirectory/config/rclone:/config/rclone \
        --volume Build.SourcesDirectory/root:/root \
        --env-file=$(secureEnv.secureFilePath) \
        --env RCLONE_DRIVE_SERVICE_ACCOUNT_CREDENTIALS="$DRIVE_SERVICE_ACCOUNT_CREDENTIALS" \
        rclone/rclone \
        copy --drive-shared-with-me -v /root gdrive:WalletStationDocs
